title: Akash Vijay
logo: /assets/test.jpg
description: <a href="https://www.linkedin.com/in/akashxvijay/">Linkedin</a>
description: "ECE @ UT Austin"


show_downloads: false
theme: jekyll-theme-minimal
